version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gtfs

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db:
    driver: local
