name: Check GTFS schedule & update database

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs:
      force_update:
        type: choice
        description: "Force update"
        default: "false"
        options:
          - true
          - false

env:
  SHOULD_UPDATE: ${{ github.event.inputs.force_update }}

jobs:
  updateScheduleDB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npx prisma generate --schema="${{ github.workspace }}/src/prisma/schema.prisma" && npm run build
          cd ${{ github.workspace }}/dist
          ls

      - name: Rebuild database
        uses: actions/github-script@v7
        with:
          script: |
            const { updateDB } = await import("${{github.workspace}}/dist/index.js")
            const forceUpdate = process.env.SHOULD_UPDATE === 'true';
            await updateDB(forceUpdate)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SHOULD_UPDATE: ${{ github.event.inputs.force_update }}
